# Generated by Django 4.2.30 on 2026-09-04 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ijobiy', 'Ijobiy'), ('salbiy', 'Salbiy')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kurator', models.ForeignKey(limit_choices_to={'role': 'kurator'}, on_delete=django.db.models.deletion.CASCADE, related_name='marked_statuses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='study_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Status',
                'verbose_name_plural': 'Student Statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
