# Generated by Django 6.1.1 on 2026-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurator', '0002_studentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuratorphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='kurator_photos/'),
        ),
    ]
