# Generated by Django 4.2.30 on 2026-08-25 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.CharField(choices=[('ielts_7', 'IELTS 7+'), ('general_english', 'General English'), ('rus_tili', 'Rus tili'), ('arab_tili', 'Arab tili'), ('koreys_tili', 'Koreys tili'), ('turk_tili', 'Turk tili'), ('matematika', 'Matematika'), ('ozbek_tili', "O'zbek Tili"), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('registration', "Yangi ro'yxatdan o'tish"), ('system', 'Tizim xabari'), ('assignment', 'Guruh tayinlash')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
