# Generated by Django 4.2.30 on 2026-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teachersubject_subject_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.CharField(choices=[('ielts_7', 'IELTS 7+'), ('general_english', 'General English'), ('ingliz_tili', 'Ingliz Tili'), ('rus_tili', 'Rus tili'), ('arab_tili', 'Arab tili'), ('koreys_tili', 'Koreys tili'), ('turk_tili', 'Turk tili'), ('matematika', 'Matematika'), ('ozbek_tili', "O'zbek Tili"), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix')], max_length=20),
        ),
    ]
