# Generated by Django 4.2.30 on 2026-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('ielts_7', 'IELTS 7+'), ('general_english', 'General English'), ('rus_tili', 'Rus tili'), ('arab_tili', 'Arab tili'), ('koreys_tili', 'Koreys tili'), ('turk_tili', 'Turk tili'), ('matematika', 'Matematika'), ('ozbek_tili', "O'zbek Tili"), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix')], max_length=20),
        ),
    ]
