# Generated by Django 4.2.30 on 2026-08-28 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0003_alter_group_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.CharField(choices=[('ielts_7', 'IELTS 7+'), ('general_english', 'General English'), ('ingliz_tili', 'Ingliz Tili'), ('rus_tili', 'Rus tili'), ('arab_tili', 'Arab tili'), ('koreys_tili', 'Koreys tili'), ('turk_tili', 'Turk tili'), ('matematika', 'Matematika'), ('ozbek_tili', "O'zbek Tili"), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix')], max_length=20),
        ),
        migrations.CreateModel(
            name='AdditionalTeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, choices=[('ielts_7', 'IELTS 7+'), ('general_english', 'General English'), ('ingliz_tili', 'Ingliz Tili'), ('rus_tili', 'Rus tili'), ('arab_tili', 'Arab tili'), ('koreys_tili', 'Koreys tili'), ('turk_tili', 'Turk tili'), ('matematika', 'Matematika'), ('ozbek_tili', "O'zbek Tili"), ('fizika', 'Fizika'), ('kimyo', 'Kimyo'), ('biologiya', 'Biologiya'), ('tarix', 'Tarix')], default='', max_length=20)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')])),
                ('time', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'oquvchi'}, on_delete=django.db.models.deletion.CASCADE, related_name='additional_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'qowimcha_ustoz'}, on_delete=django.db.models.deletion.CASCADE, related_name='additional_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('teacher', 'student', 'weekday')},
            },
        ),
    ]
